### ISSUE TITLE
403 Response

### ISSUE THREAD

**Issue by ALMIGHTYABE** [olofens/koinly-crypto-transaction-parser#1]
After following the mentioned steps I am receiving a Response [403] when hitting the koinly api, have you been able to run this recently, or know of any solutions.

**Comment by olofens** [comment]
Hi, sorry for not noticing this until now. 
Yes, I ran it successfully just a few months ago.

**Comment by ALMIGHTYABE** [comment]
Hi,
Thank you for your response.
I tried it again after following the instructions but was still not able to
run it. Facing a 403 as the status code.

**Comment by olofens** [comment]
@ALMIGHTYABE 403 is an interesting issue... are you getting the correct and entire request headers from the network tab? 
Here's an example of what it should look like (I redacted some stuff of course)

```
headers = {
    'authority': 'api.koinly.io',
    'caches-requests': '1',
    'x-csrf-token': 'csrf token',
    'x-portfolio-token': 'portfolio token',
    'sec-ch-ua-mobile': '?0',
    'user-agent': 'user agent',
    'accept': 'application/json, text/plain, */*',
    'x-auth-token': 'your auth token',
    'access-control-allow-credentials': 'true',
    'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="97", "Chromium";v="97"',
    'sec-ch-ua-platform': '"macOS"',
    'origin': 'https://app.koinly.io',
    'sec-fetch-site': 'same-site',
    'sec-fetch-mode': 'cors',
    'sec-fetch-dest': 'empty',
    'referer': 'https://app.koinly.io/',
    'accept-language': 'sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7',
    'cookie': 'your cookie',
}
```

**Comment by olofens** [comment]
Interesting.... I tried it myself now and I do also get a 403. Perhaps they patched this up and made it a bit harder to do. 

Closing, I won't be putting any more work into this sadly. I just pay for koinly now... much easier and worth the money :) 

Best of luck!

**Comment by ALMIGHTYABE** [comment]
All good. Was going to do the same.
